### ISSUE TITLE
关于WifiManager更新wifi配置信息的问题

### ISSUE THREAD

**Issue by jinjin123** [larrySmile02/YueWifiConnect#1]
您好，首先感谢你辛苦的工作！我看了一下你wifiscan/util/代码里的那一块

`
      if (config.networkId > 0) {

            result = wifimanager.enableNetwork(config.networkId, true);
            wifimanager.updateNetwork(config);
        } else {

            int i = wifimanager.addNetwork(config);
            result = false;
            if (i > 0) {
                wifimanager.saveConfiguration();
                return wifimanager.enableNetwork(i, true);
            }
        }

`
这两个能有效的更改配置吗? 我这边小米6测试了 updateNetwork(config)不更新配置，saveConfiguration(）保存失败
api 29

**Comment by jinjin123** [comment]
加了权限的 但是updateconfig 返回-1

**Comment by larrySmile02** [comment]
谢谢反馈！ 小米手机比较特殊，MIUI系统把连接WiFi权限设置为敏感权限，而且无法动态申请。所以小米手机需要特殊处理。有空继续优化。

**Comment by jinjin123** [comment]
明白了，谢谢！
